In [1]:
import pandas as pd
import numpy as np

In [10]:
#agrupacion de datos
dias = [ 'dia1','dia1','dia3','dia3','dia4'] 
vendedores = [ 'vendedor1','vendedor2','vendedor3','vendedor4','vendedor5'] 
ventas = [ 500,74,85, 9655, 6441] 
diccionario = { 'dias':dias  , 'vendedores': vendedores , 'ventas': ventas}

dataframe = pd.DataFrame(diccionario)

dataframe

   dias vendedores  ventas
0  dia1  vendedor1     500
1  dia1  vendedor2      74
2  dia3  vendedor3      85
3  dia3  vendedor4    9655
4  dia4  vendedor5    6441

In [12]:
dataframe.groupby('dias')

In [14]:
dataframe.groupby('dias').mean('ventas')

      ventas
dias
dia1   287.0
dia3  4870.0
dia4  6441.0

In [15]:
dataframe.groupby('dias').sum('ventas')

      ventas
dias
dia1     574
dia3    9740
dia4    6441

In [17]:
dataframe.groupby('dias').max('ventas')

      ventas
dias
dia1     500
dia3    9655
dia4    6441

In [18]:
dataframe.groupby('dias').describe()

     ventas
      count    mean          std     min     25%     50%     75%     max
dias
dia1    2.0   287.0   301.227489    74.0   180.5   287.0   393.5   500.0
dia3    2.0  4870.0  6767.011896    85.0  2477.5  4870.0  7262.5  9655.0
dia4    1.0  6441.0          NaN  6441.0  6441.0  6441.0  6441.0  6441.0

In [19]:

import numpy as np
import pandas as pd

diccionario1 = {'A':[1,2,3], 'B':[4,5,6], 'C':[7,8,9]}
dataframe1 = pd.DataFrame(diccionario1)

diccionario2 = {'A':[11,12,13], 'B':[14,15,16], 'C':[17,18,19]}
dataframe2 = pd.DataFrame(diccionario2)

pd.concat([dataframe1,dataframe2])

    A   B   C
0   1   4   7
1   2   5   8
2   3   6   9
0  11  14  17
1  12  15  18
2  13  16  19

In [20]:
pd.concat([dataframe1,dataframe2], axis=1)

   A  B  C   A   B   C
0  1  4  7  11  14  17
1  2  5  8  12  15  18
2  3  6  9  13  16  19