In [10]:
##MERGE DATAFRAMES

import numpy as np
import pandas as pd


diccionario1 = {'c':[1,2,3], 'd':[4,5,6], 'clave':['c1','c2','c3']}
dataframe1 = pd.DataFrame(diccionario1)





diccionario2 = {'f':[1,2,3], 'e':[44,54,44], 'clave':['c1','c2','c3']}
dataframe2 = pd.DataFrame(diccionario2)

In [7]:
dataframe1

   c  d clave
0  1  4    c1
1  2  5    c2
2  3  6    c3

In [8]:
dataframe2

   c   d clave
0  1  44    c1
1  2  54    c2
2  3  44    c3

In [11]:
pd.merge(dataframe1, dataframe2, on= 'clave')

   c  d clave  f   e
0  1  4    c1  1  44
1  2  5    c2  2  54
2  3  6    c3  3  44