In [42]:
import pandas as pd
import numpy  as np

def calcular_promedio(dataframe):   
    datapromedio = []
    columns=[]
    for valor in dataframe:        
        promedio =dataframe[valor].mean()
        #print(promedio)    
        #data = {valor:promedio }
        #df1[valor] = promedio  
        datapromedio.append( promedio )
        columns.append(valor)        
    #data = np.array([[1, 2, 3]])
    data = np.array([datapromedio ])
    #columnas=['A', 'B', 'C']
    columnas= columns
    # Convertir a DataFrame con nombres de columnas
    df1 = pd.DataFrame(data, columns=columnas)
    return df1
        
        
    
    
    
    
# Ejemplo de uso
data = {
    'A': [1, 2, 3, 4],
    'B': [5, 6, 7, 8],
    'C': [9, 10, 11, 12]
}

df = pd.DataFrame(data)
resultado = calcular_promedio(df)
print(resultado)

resultado

     A    B     C
0  2.5  6.5  10.5

     A    B     C
0  2.5  6.5  10.5

In [41]:
df

   A  B   C
0  1  5   9
1  2  6  10
2  3  7  11
3  4  8  12