In [11]:
import numpy as np
import pandas as pd

diccionario1 = {'a':[1,2,3, 4], 'b':[4,5,6, 7] }
dataframe1 = pd.DataFrame(diccionario1, index=['i1', 'i2', 'i3', 'i4'])


diccionario2 = {'c':[11,12,13], 'd':[14,15,16]}
dataframe2 = pd.DataFrame(diccionario2 ,index=['i1', 'i2', 'i3'])

In [5]:
dataframe1

    c  d
i1  1  4
i2  2  5
i3  3  6

In [6]:
dataframe2

     c   d
i1  11  14
i2  12  15
i3  13  16

In [12]:
dataframe1.join(dataframe2)

    a  b     c     d
i1  1  4  11.0  14.0
i2  2  5  12.0  15.0
i3  3  6  13.0  16.0
i4  4  7   NaN   NaN

In [16]:
import numpy as np
import pandas as pd

diccionario1 = {'a':[1,2,3, 2], 'b':[6,5,6, 7] }
dataframe1 = pd.DataFrame(diccionario1, index=['i1', 'i2', 'i3', 'i4'])
dataframe1


dataframe1["a"].unique()  # unico

array([1, 2, 3])

In [18]:
dataframe1["a"].nunique() #no unico

3

In [19]:
dataframe1["a"].value_counts()

a
2    2
1    1
3    1
Name: count, dtype: int64

In [20]:
dataframe1["b"].value_counts()

b
6    2
5    1
7    1
Name: count, dtype: int64

In [22]:
dataframe1

    a  b
i1  1  6
i2  2  5
i3  3  6
i4  2  7

In [21]:
def multiplicar(x):
    return x*2

dataframe1["b"].apply(multiplicar)

i1    12
i2    10
i3    12
i4    14
Name: b, dtype: int64

In [23]:
 

dataframe1["b"].apply(lambda x:x*2)

i1    12
i2    10
i3    12
i4    14
Name: b, dtype: int64

In [28]:
dataframe1.drop("b", axis=1)

    a
i1  1
i2  2
i3  3
i4  2

In [29]:
dataframe1.drop("i1")

    a  b
i2  2  5
i3  3  6
i4  2  7

In [30]:
dataframe1.columns

Index(['a', 'b'], dtype='object')

In [42]:
dataframe1.index

Index(['i1', 'i2', 'i3', 'i4'], dtype='object')

In [45]:
dataframe1.sort_values('b', ascending=False)

    a  b
i4  2  7
i1  1  6
i3  3  6
i2  2  5