In [ ]:
#selectionar datos mediante condicion dataframess

In [25]:
import pandas as pd
filas = 'ventas1 ventas2 ventas3'.split()
filas
 

columnas  = 'zona1 zona2 zona3'.split()
columnas

datos = [   [123,  200,  455] , [123,  44,  300] , [123,  55,  100]   ]

datos

dataframe = pd.DataFrame(datos, filas, columnas)
dataframe

         zona1  zona2  zona3
ventas1    123    200    455
ventas2    123     44    300
ventas3    123     55    100

In [3]:
columnas  = 'zona1 zona2 zona3'.split()
columnas

['zona1', 'zona2', 'zona3']

In [14]:
datos = [   [123,  200,  455] , [123,  44,  300] , [123,  55,  100]   ]

datos

[[123, 200, 455], [123, 44, 300], [123, 55, 100]]

In [15]:
dataframe = pd.DataFrame(datos, filas, columnas)
dataframe

         zona1  zona2  zona3
ventas1    123    200    455
ventas2    123     44    300
ventas3    123     55    100

In [8]:
condicion = dataframe>200
dataframe[condicion]

         zona1  zona2  zona3
ventas1    NaN  45644    455
ventas2    NaN  45644    455
ventas3    NaN  45644    455

In [19]:
condicion = dataframe['zona1']>100
dataframe[condicion]

         zona1  zona2  zona3
ventas1    123    200    455
ventas2    123     44    300
ventas3    123     55    100

In [21]:
condicion = ( dataframe['zona1']>50)   & ( dataframe['zona3']>300)   
dataframe[condicion]

         zona1  zona2  zona3
ventas1    123    200    455

In [22]:
condicion = ( dataframe['zona1']>50)   | ( dataframe['zona3']>300)   
dataframe[condicion]

         zona1  zona2  zona3
ventas1    123    200    455
ventas2    123     44    300
ventas3    123     55    100

In [23]:
condicion = ( dataframe['zona1']>50)   | ( dataframe['zona3']>300)   
dataframe[condicion]['zona1']

ventas1    123
ventas2    123
ventas3    123
Name: zona1, dtype: int64

In [24]:
condicion = ( dataframe['zona1']>50)   | ( dataframe['zona3']>300)   
dataframe[condicion][[  'zona1' , 'zona2']]

         zona1  zona2
ventas1    123    200
ventas2    123     44
ventas3    123     55

In [26]:
import pandas as pd
filas = 'ventas1 ventas2 ventas3'.split()
filas
 

columnas  = 'zona1 zona2 zona3'.split()
columnas

datos = [   [123,  200,  455] , [123,  44,  300] , [123,  55,  100]   ]

datos

dataframe = pd.DataFrame(datos, filas, columnas)
dataframe

         zona1  zona2  zona3
ventas1    123    200    455
ventas2    123     44    300
ventas3    123     55    100

In [29]:
diasfilas = 'dia1 dia2 dia3'.split()
dataframe['dias']=diasfilas

dataframe

         zona1  zona2  zona3  dias
ventas1    123    200    455  dia1
ventas2    123     44    300  dia2
ventas3    123     55    100  dia3

In [30]:
dataframe.set_index('dias')

      zona1  zona2  zona3
dias
dia1    123    200    455
dia2    123     44    300
dia3    123     55    100