In [1]:
######dataframes como tablas

In [6]:
import numpy as np
import pandas as pd
filas =[   'ventas1','ventas2','ventas3' ]
columnas =[   'zona1','zona2','zona3' ]

datos =[   [123,4564,6545] , [123,4564,6545] , [123,4564,6545]  ]

In [7]:
dataframe= pd.DataFrame(datos, filas, columnas)
dataframe

         zona1  zona2  zona3
ventas1    123   4564   6545
ventas2    123   4564   6545
ventas3    123   4564   6545

In [8]:
dataframe.loc['ventas1']

zona1     123
zona2    4564
zona3    6545
Name: ventas1, dtype: int64

In [12]:
dataframe.loc[['ventas1', 'ventas2']]

         zona1  zona2  zona3
ventas1    123   4564   6545
ventas2    123   4564   6545

In [13]:
dataframe['zona1']

ventas1    123
ventas2    123
ventas3    123
Name: zona1, dtype: int64

In [14]:
dataframe[['zona1', 'zona2']]

         zona1  zona2
ventas1    123   4564
ventas2    123   4564
ventas3    123   4564

In [15]:
dataframe.loc['ventas1']['zona1']

np.int64(123)

In [17]:
dataframe['todaslaszonas']=dataframe['zona1']+dataframe['zona2']+dataframe['zona3'] 

dataframe

         zona1  zona2  zona3  todaslaszonas
ventas1    123   4564   6545          11232
ventas2    123   4564   6545          11232
ventas3    123   4564   6545          11232

In [19]:
dataframe.drop('todaslaszonas', axis=1)

         zona1  zona2  zona3
ventas1    123   4564   6545
ventas2    123   4564   6545
ventas3    123   4564   6545

In [21]:
dataframe.drop('todaslaszonas', axis=1, inplace=True)

KeyError: "['todaslaszonas'] not found in axis"

In [22]:
dataframe

         zona1  zona2  zona3
ventas1    123   4564   6545
ventas2    123   4564   6545
ventas3    123   4564   6545

In [23]:
dataframe.drop('ventas1', inplace=True)

In [24]:
dataframe

         zona1  zona2  zona3
ventas2    123   4564   6545
ventas3    123   4564   6545